

services:
  db:
    image: postgres:14
    container_name: postgres-campito
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campito-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-campito
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - campito-net

  backend:
    build: ./backend
    container_name: springboot-campito
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME} # Se conecta usando el nombre del servicio 'db'
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev} # Por defecto 'dev' si no se especifica
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3100}
    networks:
      - campito-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-campito
    depends_on:
      - backend
    networks:
      - campito-net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  campito-net: