

services:
  backend:
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # En un entorno de produccion real, las siguientes variables
      # se gestionarian de forma segura (ej. secrets de Docker o del orquestador)
      # y no se escribirian directamente en este archivo.
      # DB_NAME: nombre_db_prod
      # DB_USER: usuario_db_prod
      # DB_PASSWORD: password_db_prod
      # GOOGLE_CLIENT_ID: id_cliente_google_prod
      # GOOGLE_CLIENT_SECRET: secreto_cliente_google_prod

  frontend:
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
